apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mcp-fabric-system

resources:
  - namespace.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
#  - servicemonitor.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: kustomize
